Repository SilvanBaach/GNX_Webapp, pull requests merged in 2023-04, with the labels that each got.

#34 feat(doc): add first iteration of testing concept #12
  TESTING_CONCEPT.md
Labels: documentation

#41 fix(workflow): hotfix remove old nodejs version [NOTICKET]
  .github/workflows/automatic-tests.yml
Labels: bug

#44 feat(Bugfix-Ressources): Fixed a bug where the ressources can not be …
  server.js
Labels: bug

#35 Create Dashboard and Navbar [#32]
  css/dashboard.css
  server.js
  views/dashboard.ejs
Labels: enhancement

#52 fix(Tests): add jest to dependencies [#51]
  package-lock.json
  package.json
Labels: bug

#64 Added settings page
  css/components/shadowbox.css
  css/dashboard/settings.css
  js/clientJS/imgUploadToDB.js
  js/clientJS/passwordChecker.js
  package-lock.json
  package.json
  routes/dashboardRouter.js
  routes/userRouter.js
  server.js
  views/dashboard.ejs
  views/dashboard/settings.ejs
Labels: enhancement

#66 Add team calendar
  css/components/table.css
  css/dashboard/calendar.css
  js/clientJS/popupFactory.js
  js/clientJS/teamCalendar.js
  package-lock.json
  routes/dashboardRouter.js
  routes/presenceRouter.js
  routes/userRouter.js
  server.js
  views/dashboard.ejs
  views/dashboard/calendar.ejs
Labels: enhancement

#67 Add registration pages
  css/registration/address.css
  css/registration/gameaccounts.css
  css/registration/name.css
  css/registration/register.css
  css/registration/registrationsuccess.css
  routes/registerRouter.js
  server.js
  views/registration/FOLDER_FOR_REGISTRATION_VIEWS
  views/registration/address.ejs
  views/registration/gameAccounts.ejs
  views/registration/name.ejs
  views/registration/register.ejs
  views/registration/success.ejs
Labels: enhancement

#68 Add Login Enhancements
  css/login.css
  css/nav.css
  css/resetPassword.css
  css/resetPasswordEmail.css
  css/style.css
  html/nav.html
  html/resetPasswordEmail.html
  js/clientJS/toastMessages.js
  js/serverJS/database/dbConfig.js~- Installed Bootstrap - Installed EJS - Made basic project structure - EJS example
  js/serverJS/database/dbConfig.js~develop
  js/serverJS/email/emailSender.js
  js/serverJS/passportConfig.js
  package-lock.json
  package.json
  res/logo/logo_webheader_blue.jpg
  res/teams/checkmark_white.jpg
  res/teams/reload.png
  res/teams/reload_white.jpg
  routes/resetPasswordRouter.js
  routes/userRouter.js
  server.js
  views/index.ejs
  views/inputNewPassword.ejs
  views/login.ejs
  views/resetPassword.ejs
Labels: enhancement

#79 Add .env.example [#65]
  .env
  .env.example
Labels: enhancement, good first issue
