Repository SilvanBaach/GNX_Webapp, pull requests merged in 2023-05, with the labels that each got.

#75 Link Logo to Index Page
  html/nav.html
Labels: enhancement

#69 56 create the teammanagement page
  css/dashboard/teammanagement.css
  css/library/anyPaginator.css
  js/clientJS/teammanagement.js
  js/library/anyPaginator.js
  routes/dashboardRouter.js
  routes/teamRouter.js
  routes/teamTypeRouter.js
  server.js
  views/dashboard.ejs
  views/dashboard/teammanagement.ejs
Labels: enhancement

#87 Set up fail2ban
  .github/workflows/auto-deploy.yml
  Caddyfile
Labels: enhancement, good first issue

#88 Import Fonts intoproject
  css/style.css
  fonts/Montserrat-VariableFont_wght.ttf
  fonts/Orbitron-VariableFont_wght.ttf
Labels: enhancement

#90 Update auto-deploy and auto-deploy-prod
  .github/workflows/auto-deploy-prod.yml
Labels: bug

#92 Implement key based ssh authentication
  .github/workflows/auto-deploy-prod.yml
  .github/workflows/auto-deploy.yml
Labels: enhancement

#94 57 create user management
  css/dashboard/usermanagement.css
  js/clientJS/usermanagement.js
  routes/dashboardRouter.js
  routes/registrationCodeRouter.js
  routes/teamTypeRouter.js
  routes/userRouter.js
  server.js
  views/dashboard.ejs
  views/dashboard/usermanagement.ejs
Labels: enhancement

#100 feat(Calendar-bug): HOTFIX: Deleted the export method so that all met…
  js/clientJS/teamCalendar.js
Labels: bug

#76 Create Filestorage
  .github/workflows/auto-deploy-prod.yml
  .github/workflows/auto-deploy.yml
  css/dashboard/fileshare.css
  docker-compose.yml
  filestorage/root/Bildmarke_white.png
  filestorage/root/Test/IMG_3213.jpeg
  filestorage/root/Test/Test2/IMG_3213.jpeg
  js/clientJS/fileshareClient.js
  js/serverJS/fileshareServer.js
  package-lock.json
  package.json
  res/fileIcons/Bildmarke_white.png
  res/logo/Bildmarke_white.png
  routes/dashboardRouter.js
  routes/fileshareRouter.js
  routes/registerRouter.js
  routes/userRouter.js
  server.js
  views/dashboard.ejs
  views/dashboard/fileshare.ejs
  views/login.ejs
  views/register.ejs
  views/registration/register.ejs
Labels: enhancement
